// max app code value is 40. we must appCode generate above (10 to 40).
// Need to check app code is available in Integration server.

export enum AppCode {
    all = "*",
    dev = "01",
    test = "02",
    sandboxUAT = "04",
    Flexbank = "10",
    Connect = "11",
    SG_6GMustafaPay = "12",
    YourPay = "13",
    SG_6GPay = "14",
    FortuneTech = "15",
    Transfez = "16",
    DazzlingXchange = "17",
    HalongPay = "20",
    Agrani = "21",
    SG_Connect = "22",
    Zhongguo = "23",
    JDee = "24",
    MetroRemit = "25",
    beamNGoLive = "26",
    adbLive = "27",
    kingsRemitLive = "28",
    PhlUAT = "29",
    PhlLive = "30",
    JufuUat = "31",
    JufuLive = "32",
    ATT = "33",
    CrownExchange = "34",
    PERKD = "35",
    LMPay = "36",
    FlexMPay = "37",
    Steadfast = "38",
    PayGo = "39",
}